version:  '3.3'

services:
  nginx:
    image: nginx:1.15.3-alpine
    container_name: nginx
    restart: always
    volumes:
      - './api/public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '8001:80'
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php
    restart: always
    volumes:
      - './api/:/usr/src/app:cached'
      - './docker/php/config/php.ini:/usr/local/etc/php/conf.d/php.ini'

  postgres:
    image: postgres:13.3
    container_name: postgres
    restart: always
    volumes:
      - '/var/lib/postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
